config/routes.rb
TikcetRails::Application.routes.draw do
  

  

  

  get "events_board/show"

  get "events_board/index"
  
  

  resources :shows	
  match 'cities/:city' => 'shows#by_city', :as => :show_by_city

  resources :rooms do
    resources :events do
       get :autocomplete_show_name, :on => :collection
       collection do
	 put :show_serie
       end
    end
  end
 resources :events
  resources :theaters do
    
    resources :rooms
  end
  

  devise_for :users

  resources :selections

  get "ticket/index"

  resources :films do
    get :autocomplete_user_name, :on => :collection
  end
  
  match 'events/:serie_id/show_serie' => 'events#show_serie', :as => :show_event_serie
  match 'events/remove_serie/:serie_id' => 'events#remove_serie', :as => :remove_event_serie
  match 'events/:id' => 'events#show', :as => :event_path
  
  
   resources :address do
     get :autocomplete_city_name, :on => :collection
  end

  

  root to: 'events_board#index', as: 'events_board'

end

app/models/event.rb
class Event < ActiveRecord::Base
  
  attr_accessible :date, :event_duration ,:exception, :name, :stall_total, :show_id, :image_attributes
  
  
  
  validates_presence_of :room_id 
  validates_date :date , :after => (Time.now - 2.day)
  validates :name, :length => { :minimum => 2 }  
  validates_numericality_of :event_duration , :greater_than => 0
  
  RECURRENCE = [["Daily","daily"],["Weekly","weekly"],["Monthly","monthly"]]
 
  DAILY_RECURRENCE=[["1 Day",1],["2 Days",2],["3 Days",3],["4 Days",4],["5 Days",5],["6 Days",6],["7 Days",7]]
  
  WEEKLY_RECURRENCE=[["Monday",1],["Tuesday",2],["Wednesday",3],["Thursday",4],["Friday",5],["Saturday",6],["Sunday",7]]

  MONTHLY_RECURRENCE=[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31]
  
  after_validation :calculate_end_date

  belongs_to :room
  belongs_to :show
  belongs_to :image
  before_save :default_image
  
  accepts_nested_attributes_for :image
  
  scope :uniq_list , :select => ("DISTINCT ON (serie_id) *")
  
  def check_overriding
    
    concurrent = Event.first(:conditions =>["date > ? AND end_date < ?", self.date,self.date])
    raise "Another value exists" if concurrent.present?
    
  end
  
  def duration
    (self.end_date-self.date)
  end
  
  def is_serie
    
    if self.serie_id == 0
       return false
    else
      
      true
    end
    
  end
  
  private
  
  def calculate_end_date    
    self.end_date = self.date + self.event_duration.hours
  end

  def default_image
    
     if self.show_id != 0 
       show = Show.find(self.show_id)
       self.build_image
       self.image_id = show.image_id
       
     end
  end


  
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  # GET /events
  # GET /events.json
  include IceCube
  before_filter :load_room
  before_filter :get_show_id  , :only => [:create, :update]
  after_filter :recurrences_save, :only => [:create, :update]
  after_filter :session_trace

  autocomplete :show, :name, :full => true
    
    load_and_authorize_resource :only => [:new, :update, :create, :destroy]

  def remove_serie
   #@event  = Event.where(:serie_id => params[:serie_id]).first
    Event.destroy_all("serie_id = #{params[:serie_id]}")
    respond_to do |format|
      format.html {
     render :nothing => true, :status => 200, :content_type => 'text/html'    
      }
    end   
  end
  
  
  
  def index
    @events = @room.events.all

   @the_list = theme_variables(@events)
        
        render "shared/_list_of_items"
  end
  
  def show_serie
    @events = Event.where("serie_id  = #{params[:serie_id]}")
    @room=""
    respond_to do |format|
      format.html {# show.html.erb
      #render "events/show_serie"
    #
    render "show_serie", :locals => { :events => @events }, :layout => false
    
      }

    end

    
  end

  # GET /events/1
  # GET /events/1.json
  def show
    @event = Event.includes(:room, :image).find(params[:id])
    
    @room = @event.room
    @theater = Theater.find(@room.theater_id)
    
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @event }
    end
  end

  # GET /events/new
  # GET /events/new.json
  def new
    @event = @room.events.build
    @event.show_id = 0
    @event.build_image
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @event }
    end
  end

  # GET /events/1/edit
  def edit
    @event = Event.find(params[:id])
  end

  # POST /events
  # POST /events.json
  def create
    
    @event = @room.events.build(params[:event])
    
    
    respond_to do |format|
      if @event.save
        format.html { redirect_to @room, notice: 'Event was successfully created.' }
        format.json { render json: @event, status: :created, location: @event }
      else
        format.html { render action: "new" }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /events/1
  # PUT /events/1.json
  def update
    @event = Event.includes(:room,:image).find(params[:id])
    @room = @event.room
    
    get_show_id
   # @event.show_id = 2
    respond_to do |format|
      if @event.update_attributes(params[:event])
        
        format.html { redirect_to @room, notice: 'Event was successfully updated' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1dsdvcsd
  # DELETE /events/1.json
  def destroy
    @event = Event.find(params[:id])
    @event.destroy

    respond_to do |format|
      format.js { render "delete_event"}
      format.html { redirect_to @room }
      format.json { head :no_content }
    end
  end
  
  def load_room
    if params[:room_id].present?
      @room = Room.find(params[:room_id])
      @theater = Theater.find(@room.theater_id)
    end
   
  end

  def get_show_id 
   
    params[:event][:show_id] = params[:show_id_hidden]
    
  end
  
  private
  
 
  
  def recurrences_save

    if(params[:recurrence][:every]!="")
      
      #day when the recurrence event is starting
      if @event.serie_id == 0
        @event.serie_id = @event.id
        @event.save
      end
      start_day = @event.date.to_time
      l = (params[:recurrence][:end_date].to_s)
      
      #final day for the recurrence
      final_day = Date.strptime(l,'%m/%d/%Y').to_time
      #carefull with infinite rules!!! 
      final_day = start_day + 1.year if final_day > start_day + 1.year
      schedule = Schedule.new(start_day)
      recurrence_value = 1
      
       
      if(params[:recurrence][:every]==Event::RECURRENCE[0][1].to_s)
        recurrence_value = params[:recurrence][:daily].to_f
        schedule.add_recurrence_rule Rule.daily(recurrence_value)
      
        end
      if(params[:recurrence][:every]==Event::RECURRENCE[1][1].to_s)
        
        recurrence_value = params[:recurrence][:weekly]
         schedule.add_recurrence_rule eval("Rule.weekly(1).day(#{recurrence_value.join(',')})")
        #schedule.add_recurrence_rule Rule.daily(recurrence_value)
      end
      
       if(params[:recurrence][:every]==Event::RECURRENCE[2][1].to_s)
        logger.fatal params[:recurrence][:every].to_s
        recurrence_value = params[:recurrence][:monthly]
        logger.fatal eval("Rule.monthly(1).day_of_month(#{recurrence_value.join(',')})").to_s
        
         schedule.add_recurrence_rule eval("Rule.weekly(1).day_of_month(#{recurrence_value.join(',')})")
        #schedule.add_recurrence_rule Rule.daily(recurrence_value)
      end
      
      
      
          i = 0
          Event.transaction do 
          
          schedule.each_occurrence do |t|
          
          var_name = "@event" + i.to_s
          params[:event][:image_attributes][:file]= ""
          
          current_event=self.instance_variable_set(var_name,@room.events.build(params[:event]))
          current_event.build_image
          current_event.serie_id = @event.serie_id
          current_event.image_id = @event.image_id
          current_event.date = t
          
          
          current_event.save if i!=0
          
            i += 1
            break if t > final_day
           
          end
          end
    
  
      
    end
    
  end
  
  def session_trace
    
    logger.fatal session.to_s
    
  end

  
end

app/controllers/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.erb
<%= form_for([@room,@event]) do |f| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% @event.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :date %><br />
    <%= f.datetime_select :date %>
  </div>
  <div class="field">
    <%= f.label :event_duration %><br />
    <%= f.number_field :event_duration, :value => 1 %>(in hours)
  </div>

   <%= f.fields_for :image do |images| %>
  
 
    <%= render :partial => 'shared/image', :locals => {:f => images }%>

  <% end %>
  
  <div class="field">
    <%= f.label :stall_total %><br />
    <%= f.number_field :stall_total %>
  </div>
  
  <div id="show_related">
    <% temp = (@event.show_id!=0) ? Show.find(@event.show_id).name : "Find a show" %>
  Find a Show:<%= f.autocomplete_field :show_id, autocomplete_show_name_room_events_path,:id_element => '#show_id_hidden', :value => temp %>
 <input id="show_id_hidden" name="show_id_hidden" type="hidden" value="<%= @event.show_id %>" />
  <%#= autocomplete_field_tag 'show_name',(@event.show_id.present?) ? Show.find(@event.show_id).name : "Find a film" ,autocomplete_show_name_room_events_path, :size => 25 ,:id_element => '#id'%>
  
  </div>
  This fields are going to create recurrence events in combination with the ice-cube gem
  <div id = "recurrence_box">
    <%= label_tag "Recurrence every" %>
    <%= select_tag "recurrence[every]", options_for_select(Event::RECURRENCE),{:include_blank => true}%>
   
    
    <div id="recurrence_fields">
      
 
    
    <div id="selector_daily">
      <%= label_tag "Daily" %>
      <%= select_tag "recurrence[daily]", options_for_select(Event::DAILY_RECURRENCE,Event::DAILY_RECURRENCE[2]), {}%>
    </div>
    <div id="selector_weekly">
     
      <%= label_tag "Weekly" %>
      <%= select_tag "recurrence[weekly]", options_for_select(Event::WEEKLY_RECURRENCE,Event::WEEKLY_RECURRENCE[1]), { :style => "height:140px;width:120px",:multiple => true}%>
    </div>
    
     <div id="selector_monthly">
    
      <%= label_tag "Monthly" %>
      <%= select_tag "recurrence[monthly]", options_for_select(Event::MONTHLY_RECURRENCE,Event::MONTHLY_RECURRENCE[1]), {:include_blank => true, :multiple => true}%>
    </div>
     <div id="end_date"
      <%= label_tag "End Date" %>
      <%= text_field_tag "recurrence[end_date]",(Time.now + 1.month).strftime("%m/%d/%Y") %>
    </div>
    </div>
  </div>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1>Editing event</h1>

<%= render 'form' %>

<%= link_to 'Show', [@room,@event]%> |
<%= link_to 'Back', @room %>

app/views/events/index.html.erb
<h1>Listing events</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Date</th>
    <th>Stall available</th>
    <th>Stall reserve</th>
    <th>Stall total</th>
    <th>Exception</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @events.each do |event| %>
  <tr>
    <td><%= event.name %></td>
    <td><%= event.date %></td>
    <td><%= event.stall_available %></td>
    <td><%= event.stall_reserve %></td>
    <td><%= event.stall_total %></td>
    <td><%= event.exception %></td>
    <td><%= link_to 'Show', event %></td>
    <td><%= link_to 'Edit', edit_event_path(event) %></td>
    <td><%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Event', new_event_path %>

app/views/events/new.html.erb
<h1>New event</h1>

<%= render 'form' %>

<%= link_to 'Back', @room %>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>

 <div class="image">
      <%= image_tag @event.image.file_url(:thumb) if @event.image.file? %>
    </div>

<p>
  <b>Name:</b>
  <%= @event.name %>
</p>

<p>
  <b>Date:</b>
  <%= @event.date %>
</p>

<p>
  <b>Stall available:</b>
  <%= @event.stall_available %>
</p>

<p>
  <b>Stall reserve:</b>
  <%= @event.stall_reserve %>
</p>

<p>
  <b>Stall total:</b>
  <%= @event.stall_total %>
</p>

<p>
  <b>Exception:</b>
  <%= @event.exception %>
</p>

<% if can?  :update,@event  %>
  <%= link_to 'Edit', edit_room_event_path(@room,@event) %> |
<% end %>
<%= link_to 'Back', @room %>

app/views/events/show_serie.html.erb
  <tr>
    <td colspan="9">
      <a id="hide-serie" data-serie="belongs-to-serie-<%= @events.first.serie_id %>">Hide this serie</a>
    </td>
  </tr>
<% @events.each do |event| %>

  <tr class="belongs-to-serie-<%= event.serie_id %>">
    <td><%=  ( event.is_serie )?  "no": "yes" %></td>
    <td><%= event.name %></td>
    <td><%= event.date %></td>
    <td><%= event.stall_available %></td>
    <td><%= event.stall_reserve %></td>
    <td><%= event.exception %></td>
   
         <td><%= link_to 'Show',room_event_path(event.room_id,event) %></td>
     <td><%= link_to 'Edit',edit_room_event_path(event.room_id,event) %></td>
      <td><%= link_to 'destroy',room_event_path(event.room_id,event),:remote => true, method: :delete, data: {confirm: "Are you sure?"} %></td>
     
         

   </tr>
    <% end %>