config/routes.rb
TikcetRails::Application.routes.draw do
  

  

  

  get "events_board/show"

  get "events_board/index"
  
  

  resources :shows	
  match 'cities/:city' => 'shows#by_city', :as => :show_by_city

  resources :rooms do
    resources :events do
       get :autocomplete_show_name, :on => :collection
       collection do
	 put :show_serie
       end
    end
  end
 resources :events
  resources :theaters do
    
    resources :rooms
  end
  

  devise_for :users

  resources :selections

  get "ticket/index"

  resources :films do
    get :autocomplete_user_name, :on => :collection
  end
  
  match 'events/:serie_id/show_serie' => 'events#show_serie', :as => :show_event_serie
  match 'events/remove_serie/:serie_id' => 'events#remove_serie', :as => :remove_event_serie
  match 'events/:id' => 'events#show', :as => :event_path
  
  
   resources :address do
     get :autocomplete_city_name, :on => :collection
  end

  

  root to: 'events_board#index', as: 'events_board'

end

app/models/film.rb
class Film < ActiveRecord::Base
  attr_accessible :description, :genre, :name
  has_and_belongs_to_many :shows
  
end

app/controllers/films_controller.rb
class FilmsController < ApplicationController
  # GET /films
  # GET /films.json
  load_and_authorize_resource
  autocomplete :user, :email, :full => true
  def index
    @films = Film.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @films }
    end
  end

  # GET /films/1
  # GET /films/1.json
  def show
    @film = Film.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @film }
    end
  end

  # GET /films/new
  # GET /films/new.json
  def new
    @film = Film.new
    @film.build_image
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @film }
    end
  end

  # GET /films/1/edit
  def edit
    @film = Film.find(params[:id])
  end

  # POST /films
  # POST /films.json
  def create
    @film = Film.new(params[:film])

    respond_to do |format|
      if @film.save
        format.html { redirect_to @film, notice: 'Film was successfully created.' }
        format.json { render json: @film, status: :created, location: @film }
      else
        format.html { render action: "new" }
        format.json { render json: @film.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /films/1
  # PUT /films/1.json
  def update
    @film = Film.find(params[:id])

    respond_to do |format|
      if @film.update_attributes(params[:film])
        format.html { redirect_to @film, notice: 'Film was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @film.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /films/1
  # DELETE /films/1.json
  def destroy
    @film = Film.find(params[:id])
    @film.destroy

    respond_to do |format|
      format.html { redirect_to films_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/helpers/films_helper.rb
module FilmsHelper
end

app/views/films/_form.html.erb
<%= form_for(@film) do |f| %>
  <% if @film.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@film.errors.count, "error") %> prohibited this film from being saved:</h2>

      <ul>
      <% @film.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :genre %><br />
    <%= f.text_field :genre %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/films/edit.html.erb
<h1>Editing film</h1>

<%= render 'form' %>

<%= link_to 'Show', @film %> |
<%= link_to 'Back', films_path %>

app/views/films/index.html.erb
<h1>Listing films</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th>Genre</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @films.each do |film| %>
  <tr>
    <td><%= film.name %></td>
    <td><%= film.description %></td>
    <td><%= film.genre %></td>
    <td><%= link_to 'Show', film %></td>
    <td><%= link_to 'Edit', edit_film_path(film) %></td>
    <td><%= link_to 'Destroy', film, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Film', new_film_path %>

app/views/films/new.html.erb
<h1>New film</h1>

<%= render 'form' %>

<%= link_to 'Back', films_path %>

app/views/films/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @film.name %>
</p>

<p>
  <b>Description:</b>
  <%= @film.description %>
</p>

<p>
  <b>Genre:</b>
  <%= @film.genre %>
</p>


<%= link_to 'Edit', edit_film_path(@film) %> |
<%= link_to 'Back', films_path %>