config/routes.rb
TikcetRails::Application.routes.draw do
  

  

  

  get "events_board/show"

  get "events_board/index"
  
  

  resources :shows	
  match 'cities/:city' => 'shows#by_city', :as => :show_by_city

  resources :rooms do
    resources :events do
       get :autocomplete_show_name, :on => :collection
       collection do
	 put :show_serie
       end
    end
  end
 resources :events
  resources :theaters do
    
    resources :rooms
  end
  

  devise_for :users

  resources :selections

  get "ticket/index"

  resources :films do
    get :autocomplete_user_name, :on => :collection
  end
  
  match 'events/:serie_id/show_serie' => 'events#show_serie', :as => :show_event_serie
  match 'events/remove_serie/:serie_id' => 'events#remove_serie', :as => :remove_event_serie
  match 'events/:id' => 'events#show', :as => :event_path
  
  
   resources :address do
     get :autocomplete_city_name, :on => :collection
  end

  

  root to: 'events_board#index', as: 'events_board'

end

app/models/room.rb
class Room < ActiveRecord::Base
  attr_accessible  :description, :name, :repetition_rule, :stall_total, :start_on ,:finish_on
  attr_accessor :extra_values
  
  has_many :events , :dependent => :destroy
  belongs_to :theater
  


end

app/controllers/helpers/rooms_helper.rb
module RoomsHelper
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  # GET /rooms
  # GET /rooms.json
  load_and_authorize_resource
  before_filter :load_theater
  def index
    @rooms = @theater.rooms.all
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @rooms }
    end
  end

  # GET /rooms/1
  # GET /rooms/1.json
  def show
    @room = Room.includes(:theater).find(params[:id])
    Event.transaction do
      @events1=@room.events.uniq_list
      @events2=@room.events.where(:serie_id => 0)
    end
    @events = (@events1 | @events2)
    @theater = @room.theater
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @room }
    end
  end

  # GET /rooms/new
  # GET /rooms/new.json
  def new
    
    @room = @theater.rooms.build
   # @room = Room.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @room }
    end
  end

  # GET /rooms/1/edit
  def edit
    @room = Room.find(params[:id])    
  end

  # POST /rooms
  # POST /rooms.json
  def create
    @room = @theater.rooms.build(params[:room])
    @room.extra_values = (params[:start_on])
    
    
    
    respond_to do |format|
      if @room.save
        format.html { redirect_to @theater, notice: 'Room was successfully created.' }
        format.json { render json: @room, status: :created, location: @room }
      else
        format.html { render action: "new" }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /rooms/1
  # PUT /rooms/1.json
  def update
    @room = Room.find(params[:id])
    
    respond_to do |format|
      if @room.update_attributes(params[:room])
        format.html { redirect_to @room, notice: 'Room was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end


  # DELETE /rooms/1
  # DELETE /rooms/1.json
  def destroy
    @room = Room.find(params[:id])
    @room.destroy

    respond_to do |format|
      format.html { redirect_to url_for(@theater) }
      format.json { head :no_content }
      
    end
  end
    def load_theater
      if params[:theater_id].present?
         @theater = Theater.find(params[:theater_id])
      end
  
  end
end

app/views/rooms/_form.html.erb
<%= form_for([@theater,@room]) do |f| %>
  <% if @room.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@room.errors.count, "error") %> prohibited this room from being saved:</h2>

      <ul>
      <% @room.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>

  </div>
  <div class="field">
    <%= f.label :stall_total %><br />
    <%= f.number_field :stall_total %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/rooms/_list_events.html.erb
<b class="listing">Listing events</b>


<table>
  <tr>
    <th> </th>
   
    <th>Name  </th>
    <th>Date</th>

    <th>Exception</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>


<% @events.each do |event| %>
  <tr id="serie-<%= event.serie_id%>">
  <td> <%= image_tag event.image.file_url(:nano_thumb_50) if event.image.file? %>    </td>
    
    <td><h4><%= event.name %></h4></td>
    <td><%= event.date.strftime("%Y-%m-%d")  %><br/><%= event.date.strftime("%H:%M")  %></td>
    <td><%= event.exception %></td>
    <% if event.is_serie %>
      <td colspan="2"><%= link_to 'Show serie',show_event_serie_path(event.serie_id.to_i),:id => "is-ajax-#{event.serie_id}",:remote => true,:update => "serie-#{event.serie_id}"%></td>
      <td > <%= link_to 'Remove serie',remove_event_serie_path(event.serie_id), :data => {:serie => event.serie_id } , :id => "remove-serie-#{event.serie_id}",:remote => true, method: :delete ,:update => "serie-#{event.serie_id}",data: {confirm: "Are you sure?"}%></td>
          
       <%else%>
         <td><%= link_to 'Show',room_event_path(@room,event) %></td>
     <td><%= link_to 'Edit',edit_room_event_path(@room,event) %></td>
      <td><%= link_to 'destroy',room_event_path(@room,event),:remote => true, data: {confirm: "Are you sure?"} %></td>
     
         
    <% end %>
   </tr>
    <% end %>
</table>

<br />

app/views/rooms/edit.html.erb
<h1>Editing room</h1>

<%= render 'form' %>

<%= link_to 'Show', @room %> |
<%= link_to 'Back', rooms_path %>

app/views/rooms/index.html.erb
<h1>Listing rooms</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th>Repetition rule</th>
    <th>Stall total</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @rooms.each do |room| %>
  <tr>
    <td><%= room.name %></td>
    <td><%= room.description %></td>
    <td><%= room.repetition_rule %></td>
    <td><%= room.stall_total %></td>
    <td><%= link_to 'Show', room %></td>
    <td><%= link_to 'Edit', edit_room_path(room) %></td>
    <td><%= link_to 'Destroy', room, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Room', new_room_path %>

app/views/rooms/new.html.erb
<h1>New room</h1>

<%= render 'form' %>

<%= link_to 'Back', rooms_path %>

app/views/rooms/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  
  <h2><%= link_to @theater.name, @theater%></h2>
   <h1><%= @room.name %></h1>
</p>

<p>
 
  <%= @room.description %>
</p>


<div id="sessions">
  <%= render "list_events", :events => @events %>
  <p><%= link_to "Session", new_room_event_path( @room) %></p>
 
  
</div>


<%= link_to 'Edit', edit_room_path(@room) %> |
<%= link_to 'Back', @theater %>