config/routes.rb
TikcetRails::Application.routes.draw do
  

  

  

  get "events_board/show"

  get "events_board/index"
  
  

  resources :shows	
  match 'cities/:city' => 'shows#by_city', :as => :show_by_city

  resources :rooms do
    resources :events do
       get :autocomplete_show_name, :on => :collection
       collection do
	 put :show_serie
       end
    end
  end
 resources :events
  resources :theaters do
    
    resources :rooms
  end
  

  devise_for :users

  resources :selections

  get "ticket/index"

  resources :films do
    get :autocomplete_user_name, :on => :collection
  end
  
  match 'events/:serie_id/show_serie' => 'events#show_serie', :as => :show_event_serie
  match 'events/remove_serie/:serie_id' => 'events#remove_serie', :as => :remove_event_serie
  match 'events/:id' => 'events#show', :as => :event_path
  
  
   resources :address do
     get :autocomplete_city_name, :on => :collection
  end

  

  root to: 'events_board#index', as: 'events_board'

end

app/models/theater.rb
class Theater < ActiveRecord::Base
  attr_accessible :description, :name, :address_attributes, :image_attributes
  
  has_many :rooms , :dependent => :destroy
  has_one :address , :as => :addressable ,:dependent => :destroy
  belongs_to :image, :dependent => :destroy
  accepts_nested_attributes_for :address
  accepts_nested_attributes_for :image
  

  
  
end

app/controllers/helpers/theaters_helper.rb
module TheatersHelper
end

app/controllers/theaters_controller.rb
class TheatersController < ApplicationController
  # GET /theaters
  # GET /theaters.json
  
  load_and_authorize_resource
  
  def index
    @theaters = Theater.all

   @the_list = theme_variables(@theaters)
        
        render "shared/_list_of_items"
  end

  # GET /theaters/1
  # GET /theaters/1.json
  def show
    @theater = Theater.includes(:rooms, :image).find(params[:id])
    @rooms = @theater.rooms
    
   
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @theater }
    end
  end

  # GET /theaters/new
  # GET /theaters/new.json
  def new
    @theater = Theater.new
    @theater.build_address
    @theater.build_image
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @theater }
    end
  end

  # GET /theaters/1/edit
  def edit
    @theater = Theater.find(params[:id])
       if @theater.address.present?
      logger.fatal "tiene direccion"
            
    end
     if !@theater.address.present?
      logger.fatal "no tiene direccion"
      @theater.build_address      
    end
  end

  # POST /theaters
  # POST /theaters.json
  def create
    @theater = Theater.new(params[:theater])

    respond_to do |format|
      if @theater.save
        format.html { redirect_to @theater, notice: 'Theater was successfully created.' }
        format.json { render json: @theater, status: :created, location: @theater }
      else
        format.html { render action: "new" }
        format.json { render json: @theater.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /theaters/1
  # PUT /theaters/1.json
  def update
    @theater = Theater.find(params[:id])
  

    respond_to do |format|
      if @theater.update_attributes(params[:theater])
        format.html { redirect_to @theater, notice: 'Theater was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @theater.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /theaters/1
  # DELETE /theaters/1.json
  def destroy
    @theater = Theater.find(params[:id])
    @theater.destroy

    respond_to do |format|
      format.html { redirect_to theaters_url }
      format.json { head :no_content }
    end
  end
end

app/views/theaters/_form.html.erb
<%= form_for @theater, :html => {:multipart => true}  do |f| %>
  <% if @theater.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@theater.errors.count, "error") %> prohibited this theater from being saved:</h2>

      <ul>
      <% @theater.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
   <%= f.fields_for :image do |images| %>
      <%= render :partial => 'shared/image', :locals => {:f => images } %>
    <% end %>
  <%= f.fields_for :address do |address| %>
    <%= render :partial => 'shared/address', :locals => {:f => address }%>
  <% end %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/theaters/_list_rooms.html.erb
<div id="room-list">
    <p class="title1">Rooms</p>
    
  <table>
    <tr>
      <th>Room name</th>
      <th>Description</th>

      <th>Stall total</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  
  <% @rooms.each do |room| %>
    <tr>
      <td><%= room.name %></td>
      <td><%= room.description %></td>

      <td><%= room.stall_total %></td>
      <td><%= link_to 'Show', theater_room_path(@theater,room)%></td>
      <td><%= link_to 'Edit', edit_theater_room_path(@theater,room) %></td>
      <td><%= link_to 'Destroy', theater_room_path(@theater,room), method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
  
  </table>
  <p><%= link_to "Create new room", new_theater_room_path(@theater) %></p>
  
  <br />

</div>

app/views/theaters/edit.html.erb
<h1>Editing theater</h1>

<%= render 'form' %>

<%= link_to 'Show', @theater %> |
<%= link_to 'Back', theaters_path %>

app/views/theaters/index.html.erb
<h1>Listing theaters</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @theaters.each do |theater| %>
  <tr>
    <td><%= theater.name %></td>
    <td><%= theater.description %></td>
    <td><%= link_to 'Show', theater %></td>
    <td><%= link_to 'Edit', edit_theater_path(theater) %></td>
    <td><%= link_to 'Destroy', theater, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Theater', new_theater_path %>

app/views/theaters/new.html.erb
<h1>New theater</h1>

<%= render 'form' %>

<%= link_to 'Back', theaters_path %>

app/views/theaters/show.html.erb
<p id="notice"><%= notice %></p>

<p >
  <b>Theater:</b>  <h2><%= @theater.name %></h2>
</p>
<b>Address:</b>
  <%= @theater.address.line1 %>
  <%= @theater.address.city %>

<p>
   <%= @theater.description %>
</p>
    <div class="image">
      <%= image_tag @theater.image.file_url(:thumb) if @theater.image.file? %>
    </div>

<p>
  
  
</p>
<%= render "list_rooms" %>

<%= link_to 'Edit', edit_theater_path(@theater) %> |
<%= link_to 'Back', theaters_path %>